/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package foodhomework;

import Classes.Mailer;
import Classes.Recipe;
import javax.swing.JOptionPane;

/**
 *
 * @author fernandocardoce
 */
public class LandingPage extends javax.swing.JFrame {

    /**
     * Creates new form LandingPage
     */
    public LandingPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlMeat = new javax.swing.JPanel();
        cbxRecMeat = new javax.swing.JComboBox<>();
        imgMeat = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAMeat = new javax.swing.JTextArea();
        lblEmailTo1 = new javax.swing.JLabel();
        txtEmailToMeat = new javax.swing.JTextField();
        btnSendMeat = new javax.swing.JButton();
        Pasta = new javax.swing.JPanel();
        cbxRecPasta = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAPasta = new javax.swing.JTextArea();
        imgPasta = new javax.swing.JLabel();
        lblEmailTo2 = new javax.swing.JLabel();
        txtEmailToPasta = new javax.swing.JTextField();
        btnSendPasta = new javax.swing.JButton();
        pnlChicken = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAChkn = new javax.swing.JTextArea();
        cbxRecChkn = new javax.swing.JComboBox<>();
        imgChkn = new javax.swing.JLabel();
        lblEmailTo = new javax.swing.JLabel();
        txtEmailToChk = new javax.swing.JTextField();
        btnSendChk = new javax.swing.JButton();
        pnlDessert = new javax.swing.JPanel();
        cbxRecDessert = new javax.swing.JComboBox<>();
        imgDessert = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtADessert = new javax.swing.JTextArea();
        lblEmailTo3 = new javax.swing.JLabel();
        txtEmailToDsst = new javax.swing.JTextField();
        btnSendDsst = new javax.swing.JButton();
        pnlSalad = new javax.swing.JPanel();
        cbxRecSalad = new javax.swing.JComboBox<>();
        imgSalad = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtASalad = new javax.swing.JTextArea();
        lblEmailTo4 = new javax.swing.JLabel();
        txtEmailToSalad = new javax.swing.JTextField();
        btnSendSalad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbxRecMeat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recipes", "Perfect Flank Steak", "Cheesesteak Potato Skins", "Salisbury Steak", "Steak Sandwich", "Cilantro-Lime Grilled Steak", "Philly Cheesesteak Soup", "Easy Beef Stroganoff", "Mongolian Beef Ramen" }));
        cbxRecMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecMeatActionPerformed(evt);
            }
        });

        txtAMeat.setEditable(false);
        txtAMeat.setColumns(20);
        txtAMeat.setLineWrap(true);
        txtAMeat.setRows(5);
        txtAMeat.setToolTipText("");
        txtAMeat.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtAMeat);

        lblEmailTo1.setText("Email To");

        btnSendMeat.setText("Send");
        btnSendMeat.setEnabled(false);
        btnSendMeat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendMeatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMeatLayout = new javax.swing.GroupLayout(pnlMeat);
        pnlMeat.setLayout(pnlMeatLayout);
        pnlMeatLayout.setHorizontalGroup(
            pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMeatLayout.createSequentialGroup()
                .addGroup(pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMeatLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailTo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailToMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendMeat))
                    .addGroup(pnlMeatLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMeatLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        pnlMeatLayout.setVerticalGroup(
            pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMeatLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMeatLayout.createSequentialGroup()
                        .addComponent(cbxRecMeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgMeat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlMeatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTo1)
                    .addComponent(txtEmailToMeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendMeat))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Meat", pnlMeat);

        cbxRecPasta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recipes", "Lassagna Rolls", "Spaghetti And Meatballs", "Spinach Lasagna", "Baked Spaghetti", "Fettuccine Alfredo", "Pasta Fagioli", "Shrimp Alfredo", "Chicken Tetrazzini" }));
        cbxRecPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecPastaActionPerformed(evt);
            }
        });

        txtAPasta.setColumns(20);
        txtAPasta.setLineWrap(true);
        txtAPasta.setRows(5);
        txtAPasta.setToolTipText("");
        txtAPasta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAPasta);

        lblEmailTo2.setText("Email To");

        btnSendPasta.setText("Send");
        btnSendPasta.setEnabled(false);
        btnSendPasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendPastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PastaLayout = new javax.swing.GroupLayout(Pasta);
        Pasta.setLayout(PastaLayout);
        PastaLayout.setHorizontalGroup(
            PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PastaLayout.createSequentialGroup()
                .addGroup(PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PastaLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailTo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailToPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendPasta))
                    .addGroup(PastaLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecPasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PastaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        PastaLayout.setVerticalGroup(
            PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PastaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PastaLayout.createSequentialGroup()
                        .addComponent(cbxRecPasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgPasta, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(PastaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTo2)
                    .addComponent(txtEmailToPasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendPasta))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pasta", Pasta);

        txtAChkn.setColumns(20);
        txtAChkn.setLineWrap(true);
        txtAChkn.setRows(5);
        txtAChkn.setToolTipText("");
        txtAChkn.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtAChkn);

        cbxRecChkn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recipes", "Jerk Chicken", "Grilled Chicken", "Chicken Zucchini Alfredo", "Garlicky Greek Chicken", "Cajun Stuffed Chicken", "Buffalo Skillet Chicken", "Lemon Chicken", "Coconut Curry Chicken" }));
        cbxRecChkn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecChknActionPerformed(evt);
            }
        });

        lblEmailTo.setText("Email To");

        btnSendChk.setText("Send");
        btnSendChk.setEnabled(false);
        btnSendChk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendChkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlChickenLayout = new javax.swing.GroupLayout(pnlChicken);
        pnlChicken.setLayout(pnlChickenLayout);
        pnlChickenLayout.setHorizontalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlChickenLayout.createSequentialGroup()
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlChickenLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailToChk, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendChk))
                    .addGroup(pnlChickenLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecChkn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlChickenLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgChkn, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        pnlChickenLayout.setVerticalGroup(
            pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChickenLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlChickenLayout.createSequentialGroup()
                        .addComponent(cbxRecChkn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgChkn, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlChickenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTo)
                    .addComponent(txtEmailToChk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendChk))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Chicken", pnlChicken);

        cbxRecDessert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recipes", "Chocolate Chip Cookies", "Brownies", "Peanut Butter Stuffed Apples", "Marshmallow Crunch Brownies", "Chocolate PB Banana Bites", "Carrot Cake", "Cheesecake Bark", "Watermelon Ice Cream" }));
        cbxRecDessert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecDessertActionPerformed(evt);
            }
        });

        txtADessert.setColumns(20);
        txtADessert.setLineWrap(true);
        txtADessert.setRows(5);
        txtADessert.setToolTipText("");
        txtADessert.setWrapStyleWord(true);
        jScrollPane5.setViewportView(txtADessert);

        lblEmailTo3.setText("Email To");

        btnSendDsst.setText("Send");
        btnSendDsst.setEnabled(false);
        btnSendDsst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendDsstActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDessertLayout = new javax.swing.GroupLayout(pnlDessert);
        pnlDessert.setLayout(pnlDessertLayout);
        pnlDessertLayout.setHorizontalGroup(
            pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDessertLayout.createSequentialGroup()
                .addGroup(pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlDessertLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailTo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailToDsst, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendDsst))
                    .addGroup(pnlDessertLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDessertLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        pnlDessertLayout.setVerticalGroup(
            pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDessertLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDessertLayout.createSequentialGroup()
                        .addComponent(cbxRecDessert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgDessert, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlDessertLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTo3)
                    .addComponent(txtEmailToDsst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendDsst))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dessert", pnlDessert);

        cbxRecSalad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recipes", "Santa Fe Chicken Salad", "Guacamole Salad", "Greek Salad", "Harvest Cobb Salad", "Shrimp Taco Salad", "Steak Taco Salad", "Kale Caesar Salad", "Quinoa Salad" }));
        cbxRecSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRecSaladActionPerformed(evt);
            }
        });

        txtASalad.setColumns(20);
        txtASalad.setLineWrap(true);
        txtASalad.setRows(5);
        txtASalad.setToolTipText("");
        txtASalad.setWrapStyleWord(true);
        jScrollPane4.setViewportView(txtASalad);

        lblEmailTo4.setText("Email To");

        btnSendSalad.setText("Send");
        btnSendSalad.setEnabled(false);
        btnSendSalad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendSaladActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSaladLayout = new javax.swing.GroupLayout(pnlSalad);
        pnlSalad.setLayout(pnlSaladLayout);
        pnlSaladLayout.setHorizontalGroup(
            pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSaladLayout.createSequentialGroup()
                .addGroup(pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlSaladLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEmailTo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmailToSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSendSalad))
                    .addGroup(pnlSaladLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRecSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlSaladLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(imgSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(63, 63, 63))
        );
        pnlSaladLayout.setVerticalGroup(
            pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSaladLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlSaladLayout.createSequentialGroup()
                        .addComponent(cbxRecSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgSalad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlSaladLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailTo4)
                    .addComponent(txtEmailToSalad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSendSalad))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salad", pnlSalad);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxRecPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecPastaActionPerformed
        String recipeName = cbxRecPasta.getSelectedItem().toString();
        String recipeType = "Pasta";
        this.txtAPasta.setText(recipe.loadRecipe(recipeName, recipeType ));
        this.imgPasta.setIcon(new javax.swing.ImageIcon(getClass().getResource(recipe.loadImageURL(recipeName, recipeType))));
        if(! cbxRecPasta.getSelectedItem().toString().equals("Recipes")){
            this.btnSendPasta.setEnabled(true);
        } else{
            this.btnSendPasta.setEnabled(false);
        }
    }//GEN-LAST:event_cbxRecPastaActionPerformed

    private void cbxRecMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecMeatActionPerformed
        String recipeName = cbxRecMeat.getSelectedItem().toString();
        String recipeType = "Meat";
        this.txtAMeat.setText(recipe.loadRecipe(recipeName, recipeType ));
        this.imgMeat.setIcon(new javax.swing.ImageIcon(getClass().getResource(recipe.loadImageURL(recipeName, recipeType))));
        if(! cbxRecMeat.getSelectedItem().toString().equals("Recipes")){
            this.btnSendMeat.setEnabled(true);
        } else{
            this.btnSendMeat.setEnabled(false);
        }
    }//GEN-LAST:event_cbxRecMeatActionPerformed

    private void cbxRecChknActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecChknActionPerformed
        String recipeName = cbxRecChkn.getSelectedItem().toString();
        String recipeType = "Chicken";
        this.txtAChkn.setText(recipe.loadRecipe(recipeName, recipeType ));
        this.imgChkn.setIcon(new javax.swing.ImageIcon(getClass().getResource(recipe.loadImageURL(recipeName, recipeType))));
        if(! cbxRecChkn.getSelectedItem().toString().equals("Recipes")){
            this.btnSendChk.setEnabled(true);
        } else{
            this.btnSendChk.setEnabled(false);
        }
    }//GEN-LAST:event_cbxRecChknActionPerformed

    private void cbxRecSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecSaladActionPerformed
      String recipeName = cbxRecSalad.getSelectedItem().toString();
        String recipeType = "Salad";
        this.txtASalad.setText(recipe.loadRecipe(recipeName, recipeType ));
        this.imgSalad.setIcon(new javax.swing.ImageIcon(getClass().getResource(recipe.loadImageURL(recipeName, recipeType))));
        if(! cbxRecSalad.getSelectedItem().toString().equals("Recipes")){
            this.btnSendSalad.setEnabled(true);
        } else{
            this.btnSendSalad.setEnabled(false);
        }
    }//GEN-LAST:event_cbxRecSaladActionPerformed

    private void cbxRecDessertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRecDessertActionPerformed
        String recipeName = cbxRecDessert.getSelectedItem().toString();
        String recipeType = "Dessert";
        this.txtADessert.setText(recipe.loadRecipe(recipeName, recipeType ));
        this.imgDessert.setIcon(new javax.swing.ImageIcon(getClass().getResource(recipe.loadImageURL(recipeName, recipeType))));
        if(! cbxRecDessert.getSelectedItem().toString().equals("Recipes")){
            this.btnSendDsst.setEnabled(true);
        } else{
            this.btnSendDsst.setEnabled(false);
        }
    }//GEN-LAST:event_cbxRecDessertActionPerformed

    private void btnSendChkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendChkActionPerformed
        String[] recipients= {this.txtEmailToChk.getText()};
        String recipeName = String.valueOf(cbxRecChkn.getSelectedItem());
        String recipeText = txtAChkn.getText();
        mailer.SendMail(recipients, recipeName, recipeText);
         JOptionPane.showMessageDialog(null,"Email send to: "+ recipients[0]);
    }//GEN-LAST:event_btnSendChkActionPerformed

    private void btnSendMeatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendMeatActionPerformed
        String[] recipients= {this.txtEmailToMeat.getText()};
        String recipeName = String.valueOf(cbxRecMeat.getSelectedItem());
        String recipeText = txtAMeat.getText();
        mailer.SendMail(recipients, recipeName, recipeText);
         
    }//GEN-LAST:event_btnSendMeatActionPerformed

    private void btnSendPastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendPastaActionPerformed
         String[] recipients= {this.txtEmailToPasta.getText()};
        String recipeName = String.valueOf(cbxRecPasta.getSelectedItem());
        String recipeText = txtAPasta.getText();
        mailer.SendMail(recipients, recipeName, recipeText);
    }//GEN-LAST:event_btnSendPastaActionPerformed

    private void btnSendDsstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendDsstActionPerformed
        String[] recipients= {this.txtEmailToDsst.getText()};
        String recipeName = String.valueOf(cbxRecDessert.getSelectedItem());
        String recipeText = txtADessert.getText();
        mailer.SendMail(recipients, recipeName, recipeText);
    }//GEN-LAST:event_btnSendDsstActionPerformed

    private void btnSendSaladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendSaladActionPerformed
         String[] recipients= {this.txtEmailToSalad.getText()};
        String recipeName = String.valueOf(cbxRecSalad.getSelectedItem());
        String recipeText = txtASalad.getText();
        mailer.SendMail(recipients, recipeName, recipeText);
    }//GEN-LAST:event_btnSendSaladActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LandingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LandingPage().setVisible(true);
            }
        });
    }
    Mailer mailer = new Mailer();
    Recipe recipe = new Recipe();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pasta;
    private javax.swing.JButton btnSendChk;
    private javax.swing.JButton btnSendDsst;
    private javax.swing.JButton btnSendMeat;
    private javax.swing.JButton btnSendPasta;
    private javax.swing.JButton btnSendSalad;
    private javax.swing.JComboBox<String> cbxRecChkn;
    private javax.swing.JComboBox<String> cbxRecDessert;
    private javax.swing.JComboBox<String> cbxRecMeat;
    private javax.swing.JComboBox<String> cbxRecPasta;
    private javax.swing.JComboBox<String> cbxRecSalad;
    private javax.swing.JLabel imgChkn;
    private javax.swing.JLabel imgDessert;
    private javax.swing.JLabel imgMeat;
    private javax.swing.JLabel imgPasta;
    private javax.swing.JLabel imgSalad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEmailTo;
    private javax.swing.JLabel lblEmailTo1;
    private javax.swing.JLabel lblEmailTo2;
    private javax.swing.JLabel lblEmailTo3;
    private javax.swing.JLabel lblEmailTo4;
    private javax.swing.JPanel pnlChicken;
    private javax.swing.JPanel pnlDessert;
    private javax.swing.JPanel pnlMeat;
    private javax.swing.JPanel pnlSalad;
    private javax.swing.JTextArea txtAChkn;
    private javax.swing.JTextArea txtADessert;
    private javax.swing.JTextArea txtAMeat;
    private javax.swing.JTextArea txtAPasta;
    private javax.swing.JTextArea txtASalad;
    private javax.swing.JTextField txtEmailToChk;
    private javax.swing.JTextField txtEmailToDsst;
    private javax.swing.JTextField txtEmailToMeat;
    private javax.swing.JTextField txtEmailToPasta;
    private javax.swing.JTextField txtEmailToSalad;
    // End of variables declaration//GEN-END:variables
}
